---
# Univariate LSTM model
---

In [21]:
# libraries importing
import numpy as np
from keras import Input
from keras.layers import LSTM, Dense, Bidirectional
from keras.models import Model
from keras.utils import plot_model

In [50]:
# split_sequence function definition
def split_sequence(sequence, n_steps) :
    X, y = list(), list()
    for i in range(len(sequence)) :
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence) - 1 :
            break
        # gather input and outpt parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [51]:
# define input sequence
raw_seq = [i*10 for i in range (10)]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)) :
    print(X[i], y[i])

[ 0 10 20] 30
[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [52]:
X.shape

(7, 3)

In [4]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

univariate lstm example

In [5]:
# define model
x0 = Input(shape = (n_steps, n_features))
x1 = LSTM(50, activation = "relu")(x0)
output = Dense(1)(x1)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

# model fitting
model.fit(X, y, epochs = 200, verbose = 1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 3234.4192
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3166.6028
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3097.9673
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3028.1519
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 2956.8901
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2883.9446
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2809.1108
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2732.2339
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2653.2253
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2572.0747
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2488.8625
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2403.7576
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2317.0186
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2228.9956
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms

In [6]:
# demonstrate prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))

y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[100.525276]]


In [7]:
# model summmary
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 50)             │        10,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31,355 (122.48 KB)

 Trainable params: 10,451 (40.82 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20,904 (81.66 KB)

univariate lstm model with 2 hidden lstm layers

In [8]:
# define model
x0 = Input(shape = (n_steps, n_features))
x1 = LSTM(50, activation = "relu", return_sequences = True)(x0)
x2 = LSTM(50, activation = "relu")(x1)
output = Dense(1)(x2)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

# model fitting
model.fit(X, y, epochs = 200, verbose = 1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 3939.7388
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3915.6233
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3891.3081
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3866.4070
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3840.6990
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3813.8440
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3785.4578
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3755.3152
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3722.9622
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3688.0339
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3650.0833
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3608.5657
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3562.9409
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3512.4280
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms

In [9]:
# make prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))

y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[102.95318]]


bidirectional LSTM

In [10]:
# define model
x0 = Input(shape = (n_steps, n_features))
x1 = Bidirectional(LSTM(50, activation = "relu"))(x0)
output = Dense(1)(x1)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

# model fitting
model.fit(X, y, epochs = 200, verbose = 1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 3721.1421
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 3622.9753
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3524.1899
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3424.6370
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 3324.0374
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3221.9602
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3118.2708
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3012.9185
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2905.8481
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2796.7898
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2685.6079
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2571.8257
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2455.0151
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2334.5745
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms

In [11]:
# make prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))

y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[100.89509]]


---
# Multivariate LSTM model
---

In [ ]:
import numpy as np

# define input/output sequence
in_seq1 = np.array(range(10, 91, 10))
in_seq2 = np.array(range(15, 96, 10))
out_seq = in_seq1 + in_seq2

array([ 25,  45,  65,  85, 105, 125, 145, 165, 185])

In [19]:
dataset = np.vstack((in_seq1, in_seq2, out_seq)).T
dataset

array([[ 10,  15,  25],
       [ 20,  25,  45],
       [ 30,  35,  65],
       [ 40,  45,  85],
       [ 50,  55, 105],
       [ 60,  65, 125],
       [ 70,  75, 145],
       [ 80,  85, 165],
       [ 90,  95, 185]])

In [ ]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps) :
    X, y = list(), list()
    for i in range(len(sequences)) :
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences) :
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix - 1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [20]:
# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)

# summarize the data
for i in range(len(X)) :
    print(X[i], y[i])

(7, 3, 2) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [23]:
# define model
n_features = X.shape[2]
x0 = Input(shape = (n_steps, n_features))
x1 = LSTM(50, activation = "relu")(x0)
output = Dense(1)(x1)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

In [25]:
plot_model(model, to_file = "multiLSTM1.png", show_shapes = True, show_layer_activations = True);

In [27]:
# fit model
history = model.fit(X, y, epochs = 200, verbose = 1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0126
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0122
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0114
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0110
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0107
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0104
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0100
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0097
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0094
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0092
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0089
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0086
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0084
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0082
Epoch 16/200
1/1 ━━

In [28]:
# demonstrate prediction
x_input = np.array([[80, 85], [90, 95], [100, 105]]).reshape((1, n_steps, n_features))
y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[205.54932]]


# Multiple output series model

In [29]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps) :
    X, y = list(), list()
    for i in range(len(sequences)) :
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond dataset
        if end_ix > len(sequences) - 1 :
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [30]:
# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)

# print the data
for i in range(len(X)) :
    print(X[i], y[i])

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


In [31]:
n_steps = 3
n_features = 3

# define model with stacked layers
x0 = Input(shape = (n_steps, n_features))
x1 = LSTM(50, activation = "relu", return_sequences = True)(x0)
x2 = LSTM(50, activation = "relu")(x1)
output = Dense(3)(x2)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

In [32]:
# fit model
model.fit(X, y, epochs = 400, verbose = 0)

In [33]:
# demonstrate prediction
x_input = np.array([[70, 75, 145], [80, 85, 165], [90, 95, 185]]).reshape((1, n_steps, n_features))
y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[100.72858 106.29895 207.121  ]]


# Multi-step LSTM Models

In [40]:
# split a multivariate sequence into samples
def split_sequence(sequences, n_steps_in, n_steps_out) :
    X, y = list(), list()
    for i in range(len(sequences)) :
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        # check if we are beyond the sequence
        if out_end_ix > len(sequences) :
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix], sequences[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [41]:
# define input sequence
raw_seq = list(range(10, 91, 10))

# choose a number of time steps
n_steps_in, n_steps_out = 3, 2

# split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)

# summarize the data
for i in range(len(X)) :
    print(X[i], y[i])

[10 20 30] [40 50]
[20 30 40] [50 60]
[30 40 50] [60 70]
[40 50 60] [70 80]
[50 60 70] [80 90]


In [42]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X.shape)

(5, 3, 1)


In [43]:
n_steps = 3
n_features = 1

# define model with stacked layers
x0 = Input(shape = (n_steps, n_features))
x1 = LSTM(50, activation = "relu", return_sequences = True)(x0)
x2 = LSTM(50, activation = "relu")(x1)
output = Dense(2)(x2)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

In [45]:
# fit model
model.fit(X, y, epochs = 500, verbose = 0)

In [46]:
# demonstrate prediction
x_input = np.array([70, 80, 90]).reshape((1, n_steps, n_features))
y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[103.01247  113.635475]]
