---
# Univariate LSTM model
---

In [17]:
# libraries importing
import numpy as np
from keras import Input
from keras.layers import LSTM, Dense, Bidirectional
from keras.models import Model

In [2]:
# split_sequence function definition
def split_sequence(sequence, n_steps) :
    X, y = list(), list()
    for i in range(len(sequence)) :
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence) - 1 :
            break
        # gather input and outpt parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [4]:
# define input sequence
raw_seq = [i*10 for i in range (10)]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)) :
    print(X[i], y[i])

[ 0 10 20] 30
[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [5]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

univariate lstm example

In [7]:
# define model
x0 = Input(shape = (n_steps, n_features))
x1 = LSTM(50, activation = "relu")(x0)
output = Dense(1)(x1)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

# model fitting
model.fit(X, y, epochs = 200, verbose = 1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 3612.1599
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 3535.6292
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 3460.1958
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3386.4163
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3314.5513
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3244.5273
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 3176.0701
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 3107.9839
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3040.7305
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2973.4202
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 2905.5759
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 2836.6619
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2766.3333
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2694.0676
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms

In [8]:
# demonstrate prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))

y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[101.15866]]


In [12]:
# model summmary
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 50)             │        10,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31,355 (122.48 KB)

 Trainable params: 10,451 (40.82 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20,904 (81.66 KB)

univariate lstm model with 2 hidden lstm layers

In [15]:
# define model
x0 = Input(shape = (n_steps, n_features))
x1 = LSTM(50, activation = "relu", return_sequences = True)(x0)
x2 = LSTM(50, activation = "relu")(x1)
output = Dense(1)(x2)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

# model fitting
model.fit(X, y, epochs = 200, verbose = 1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 3929.9539
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 3864.0198
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3794.8577
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3729.0583
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3660.5168
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3586.0376
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 3503.9956
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3412.8999
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 3311.2537
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3198.1892
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 3073.1873
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 2936.3159
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 2786.0532
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 2624.9551
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms

In [16]:
# make prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))

y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[102.49335]]


bidirectional LSTM

In [18]:
# define model
x0 = Input(shape = (n_steps, n_features))
x1 = Bidirectional(LSTM(50, activation = "relu"))(x0)
output = Dense(1)(x1)

model = Model(inputs = x0, outputs = output)
model.compile(optimizer = "adam", loss = "mse")

# model fitting
model.fit(X, y, epochs = 200, verbose = 1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4320.5737
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 4273.0649
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 4224.8018
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4175.7119
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4125.6147
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4074.3162
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 4021.6577
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 3967.4192
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 3911.4631
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 3853.6360
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3793.7983
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3731.8140
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 3667.5562
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3600.8833
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms

In [19]:
# make prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))

y_pred = model.predict(x_input, verbose = 0)
print(y_pred)

[[102.839386]]


---
# Multivariate LSTM model
---

In [20]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps) :
    X, y = list(), list()
    for i in range(len(sequences)) :
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences) :
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix - 1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)